knp_paginator:
    page_range: 5                       # plage de pagination par défaut autour de la page courante
    default_options:
        page_name: page                 # nom du paramètre de requête pour le numéro de la page
        sort_field_name: sort           # nom du paramètre de requête pour le champ de tri
        sort_direction_name: direction  # nom du paramètre de requête pour la direction du tri
        distinct: true                  # garantir que les résultats de pagination sont distincts
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # template de pagination par défaut
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # template de tri par défaut
        