knp_paginator:
    page_range: 5                       # plage de pagination par défaut autour de la page courante
    default_options:
        page_name: page                 # nom du paramètre de requête pour le numéro de la page
        sort_field_name: sort           # nom du paramètre de requête pour le champ de tri
        sort_direction_name: direction  # nom du paramètre de requête pour la direction du tri
        distinct: true                  # garantir que les résultats de pagination sont distincts
    template:
        pagination: "@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig" # sliding pagination controls template
        sortable: "@KnpPaginator/Pagination/twitter_bootstrap_v4_font_awesome_sortable_link.html.twig" # sort link template
        filtration: "@KnpPaginator/Pagination/filtration.html.twig" # filters template
        