vich_uploader:
    db_driver: orm
    mappings:
        fuploads:
            uri_prefix: /uploads/ressources
            upload_destination: '%kernel.project_dir%/public/uploads/ressources'

            namer: vich_uploader.namer_uniqid
